### ISSUE TITLE
AttributeError: 'DenseInstanceNorm' object has no attribute 'padded_mean_table'

### ISSUE THREAD

**Issue by ZzzTD** [Kaminyou/Dense-Normalization#4]
Excuse me, I encountered this issue while making predictions.

The location is in models.dn.py ,119line.
 
`x_mean = self.padded_mean_table[:, :, top:down, left:right]  # 1, C, H, W`

May I ask how to solve this problem? Thank you, sorry to bother you.

**Comment by Kaminyou** [comment]
Could you provide the details regarding how you execute our codes. I think there is no problem in our provided example (and applying to your own dataset should follow the steps similar to ones in our examples).

**Comment by ZzzTD** [comment]
> Could you provide the details regarding how you execute our codes. I think there is no problem in our provided example (and applying to your own dataset should follow the steps similar to ones in our examples).

Thank you for your reply. I have resolved this issue. Sorry to bother you
